[project]
id = "proof"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:5173"]

[studio]
enabled = true
port = 54323

[analytics]
enabled = false